#!/usr/local/bin/zsh

cat() {
    if hash ccat 2>/dev/null; then
        if [ -f "$1" ]; then
            ccat $1
        else
            echo "cat: $1: No such file or directory"
        fi
    fi
}
