#!/usr/local/bin/zsh
#
platform='unknown'
unamestr=$(uname)

if [[ "$unamestr" == 'Linux' ]]; then
    platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
    platform='osx'
elif [[ "$unamestr" == 'MINGW64_NT-6.1' ]]; then
    echo 'Fuck this shit'
    exit 1
fi

. $HOME/.zsh/exports

. $HOME/.zsh/go
. $HOME/.zsh/postgresql
. $HOME/.zsh/python
. $HOME/.zsh/ruby
. $HOME/.zsh/chef

. $HOME/.zsh/aliases
. $HOME/.zsh/key-bindings
. $HOME/.zsh/colours
. $HOME/.zsh/functions/init
. $HOME/.zsh/prompt
