#!/usr/local/bin/zsh

if [[ $platform == 'osx' ]]; then
    plist='/usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist'

    alias 'start-postgres'='launchctl load $plist'
    alias 'stop-postgres'='launchctl unload $plist'

    POSTGRESQL_VERSION=$(brew list postgresql | head -n 1 | cut -d '/' -f 6)

    export PATH=$PATH:$(brew --prefix)/Cellar/postgresql/$POSTGRESQL_VERSION/bin
fi

