#!/usr/local/bin/zsh

if [[ $platform == 'osx' ]]; then
    if [[ -d "$HOME/.gem/" ]]; then
        RUBY_VERSION=$(ls $HOME/.gem/ruby/ | tail -n 1)

        export PATH=$PATH:$HOME/.gem/ruby/$RUBY_VERSION/bin
    fi
fi

